### ISSUE TITLE
Config override issue with omg_watcher

### ISSUE THREAD

**Issue by j0nnyw** [omisego/elixir-omg#451] opened 2019-02-19 10:26 UTC
As part of the `~/config_watcher.exs` generation and setup for the `omg_watcher`, I wanted to customize the port that the watcher listens on.

When I specified the following in my `~/config_watcher.exs`:

```
use Mix.Config
config :omg_eth,
  contract_addr: "0x21c4127004b4ae732fc407dffe65d28b1d0b3594",
  txhash_contract: "0xbb2a364ded8099a9c5d11c9388d8179790fe1c497fc76796f57e159062738b95",
  authority_addr: "0xabe7a779d6b6f9cf254b62075605ef5e7129f998"

config :omg_db,
  leveldb_path: Path.join([System.get_env("HOME"), ".omg/data_watcher"])

config :omg_watcher, OMG.Watcher.Web.Endpoint,
  http: [port: 34727],
  url: [host: "localhost", port: 34727],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: [],
  server: true
```
The following error occurred when attempting to POST to the Watcher:

```
2019-02-18 14:47:16.149 [error] ⋅GenServer OMG.Watcher.Eventer terminating
** (ArgumentError) no :pubsub server configured at, please setup :pubsub in your config.

By default this looks like:

    config :my_app, MyApp.PubSub,
      ...,
      pubsub: [name: MyApp.PubSub,
      adapter: Phoenix.PubSub.PG2]
(phoenix) lib/phoenix/endpoint.ex:510: Phoenix.Endpoint.__pubsub_server__!/1
    (omg_watcher) lib/web/endpoint.ex:16: OMG.Watcher.Web.Endpoint.broadcast!/3
    (omg_watcher) lib/eventer.ex:47: anonymous fn/1 in OMG.Watcher.Eventer.handle_cast/2
(elixir) lib/enum.ex:737: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:737: Enum.each/2
    (omg_watcher) lib/eventer.ex:45: OMG.Watcher.Eventer.handle_cast/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
(stdlib) gen_server.erl:686: :gen_server.handle_msg/6
(stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

To fix this I had to add the following to my `~/config_watcher.exs` config:

`pubsub: [name: OMG.Watcher.PubSub, adapter: Phoenix.PubSub.PG2]`

This is already defined in the watchers config located here:

`apps/omg_watcher/config/config.exs`

It would appear that this config file is getting ignored/overridden by my updated `config_watcher.exs` file.

Is this the expected behaviour or should the original settings within `apps/omg_watcher/config/config.exs` be preserved if no overrides have been set in a custom config?

**Comment by pdobacz** [comment] 2019-02-20 09:42
Thank you for reporting. I've been able to reproduce this issue, and it seems to be related to how deeply `--config`-provided configuration entries are merged into the default ones.

Figuring that this behavior is a bit surprising I opened https://github.com/elixir-lang/elixir/issues/8811 to clarify.

**NOTE** For me, the error doesn't seem to manifest when `POST`ing to the watcher but on a transaction processed when validating blocks during syncing.

**WORKAROUND** Until this is clarified, the workaround would be to provide the `:omg_watcher, ..Endpoint` entry manually merged from both `omg_watcher/config/config.exs` **and** `omg_watcher/config/dev.exs`, with the desired modifications (`http` etc) applied.

**Closed** 2019-03-22 11:37 UTC
