### ISSUE TITLE
Child-chain, Watcher & Info API split

### ISSUE THREAD

**Issue by pnowosie** [omisego/elixir-omg#1065] opened 2019-10-24 12:42 UTC
As discussed on-site we want to split ch-ch, watcher and Watcher Informational API into separate repositories to simplify development of new features.

## Currently
Watcher shares a lot of code from ch-ch. Info API is build in Watcher (as a Watcher mode).
Service dependency: ch-ch & watcher depends on ethereum node. Watcher depends on ch-ch.
[pict](...)

### 1. Info API depends on Watcher
Pros: 
- Info API knows as much as the Watcher so transaction constructed on Info API data won't be rejected by Watcher (sync diff)
- Info API doesn't have to depend on ethereum node and contain event-listeners code. 

### 2. Info API depends on Ch-ch & Ethereum node
Pros:
- independence, can process ethereum events according to its rules
- data available faster

### 2+. Additional `tx.verify` watcher endpoint
As in pt 2 :point_up: but watcher exposes `tx.verify` endpoint that returns whether given tx is valid (inputs wasn't spent yet)
Proposed by @sirn. Info API can optionally consume this endpoint when used to transaction construction.

### Issues depending (anyhow) on this issue 
#1001, #1033, (... add more)

**Comment by sirn** [comment] 2019-10-25 03:51
Going to add that idea of 2+ is if someone want to run Info API without running watcher but want tx validity, they can just use `tx.verify` of public watcher address, e.g. `watcher.samrong.omg.network`

**Comment by T-Dnzt** [comment] 2019-11-01 07:28
Based on the current state of things, I'd like to recommend a new temporary option to get us off the ground ASAP and have everything we need for the upcoming milestones.

The idea is to do an early split of the informational API so that progress can be made on the frontend apps. It's not really a split though, mostly just copying the code and putting it into a new Elixir application, without changing anything in the `elixir-omg` codebase.

This new application would be acting as the backend for the frontend apps. It would need to be plugged directly on a read-only replica of a Watcher DB to get data/events about the child chain, and would listen to events from Ethereum as well. 

From those two sets of data, this app would store relevant information in its own Postgres database and compute all the user-facing data we want to expose in our end-user applications (for example, the average block time over the past X hours). 

Any of our frontend application would be able to get what they need via a web API exposed by this new informational API app.

---

Now, on why we would want to do that. 

1. First, we want to limit the changes to `elixir-omg`, for a more stable and secure codebase. And with all the audit stuff happening, the fewer things we change, the better. This is the original plan behind splitting `elixir-omg` into ch-ch/watcher/info, but it requires a big amount of work, which we won't be able to get to for a while. I don't think we can afford to wait too long to start providing analytics, exit details, deposit confirmations, etc to our users. So we need a place to implement those features that isn't `elixir-omg`.

2. So where? We actually started building a node backend for the block explorer, to store whatever was needed for the frontend. That was a good initiative because it meant progress while everyone on the elixir-omg side was busy with all the ALD work. In order to get data, we connected that app directly to a Watcher DB. Not optimal, but it works, and doesn't impact the security of the network.

3. But since we're planning to extract the informational API down the line, why not do it now and "merge" what was built as backend for the explorer with what we have in `elixir-omg` into a new app (obviously that means rewriting some of the stuff implemented in node.js) and follow the same simple approach: get data directly from the watcher DB, talk to Ethereum independently and compute stuff.

4. Later down the road, we can remove what's left of the informational API from `elixir-omg`, and refactor the info app we created to work in a cleaner way. We could still combine services, if needed, but the new work would completely replace the current API.

---

You may think it's not optimal and I agree. But I think that's the best we can do with the constraints we have. 

/discuss

**Comment by InoMurko** [comment] 2019-11-01 11:04
O hai!
`
This new application would be acting as the backend for the frontend apps. It would need to be plugged directly on a read-only replica of a Watcher DB to get data/events about the child chain, and would listen to events from Ethereum as well.
`
Could you elaborate this part? Particularly *It would need to be plugged directly on a read-only replica*.

**Comment by pnowosie** [comment] 2019-11-01 16:27
@T-Dnzt please don’t add another app in elixir-omg but fork the repo right away. Only then we’ll make a progress toward splitting. Also InfoApi can adopt Watcher’s postres without maintaining two DBs. This also frees the Watcher from constant aligning it’s infoApi part in any change made.

**Comment by InoMurko** [comment] 2019-11-01 16:34
@pnowosie how does your comment fit into the debate? :)

**Comment by pnowosie** [comment] 2019-11-01 17:09
Maybe I missunderstood Thibault comment, but to me he proposed to add another app in elixir-omg repo. I’m suggesting to fork the repo towards real split. 👐

**Comment by InoMurko** [comment] 2019-11-01 17:31
Ahaaaa. Now I get it! Yeah I think @T-Dnzt idea is to completely clone the repo. 

But my opinion is that we can do much better with far less issues of compatibility and the work could start immediately as well. Without security (performance) implications on the Watcher. Simply put, applications give enough isolation and levering OMG.Bus gives us unlimited options, by just slightly adjusting the existing codebase.

**Comment by unnawut** [comment] 2019-11-03 21:06
Hmm I don't see @T-Dnzt and @InoMurko 's approaches as mutually exclusive. We need the event bus architecture but we also need somewhere to start that will have minimum impact to `elixir-omg` and existing downstream services like block explorer, not starting from scratch with entirely new APIs and all.

So I think these can be the steps:

1. Fork `elixir-omg` codebase right away. New codebase called `elixir-omg-infoapi` (made up name)
2. Strip all code from `elixir-omg-infoapi` except for the API endpoints that solely rely on Watcher DB (the postgres one). Any API endpoint that require data outside the read replica, directly or indirectly, must be removed.
3. Point all downstream services to the new `elixir-omg-infoapi`.
4. If a downstream service rely on any removed API, it will need to live with it.

Up to this point should be very quick (matter of days). Now we have the codebase for the Informational API to start building on, that existing downstream services can still talk to in its current way. Then...

5. The childchain team strips Watcher API codebase from `elixir-omg`.
6. The informational API team updates `elixir-omg-infoapi` codebase. Starts consuming the event bus from the childchain and processing the events into its own data store. Then updates the APIs to replace all read-replica calls with calls to its own data store.

With all this, whether the Informational API need to expose data as events or RPC, `elixir-omg` does not need to care. Informational API does not need to be rebuilt from scratch. Downstream services only need to reconfig their watcher URL to work again. And we can start a faster pace Informational API development right away.

The only drawback is that some downstream services will have to deal with APIs that is no longer available. My quick look at the block explorer is that all calls go to Watcher API anyway, so this should be minimal or no impact.

**Comment by InoMurko** [comment] 2019-11-03 22:26
The approach of splitting Child Chain and Watcher has already been decided with @achiurizo. We need to finish end 2 end tests (called https://github.com/omisego/specs/ *first*). This will allow us to abandon the current integration tests bundled with Ex Unit AND be 100% we did not break the current functionality. You need to understand that there are tests for the Watcher, expecting that the code for childchain is *there* and vice versa.

I'm very, very much *convinced* that splitting or stripping the current codebase is **impossible** with the amount of tangling there is without sacrificing possible regression. 

So to be a little bit more exact in what I mean, and the approach I have in mind, and to showcase where the *border* between "informational" and "security" is ... a quick POC: https://github.com/omisego/elixir-omg/pull/1096/files 
This particular PR decouples the two modes and elevates the performance by the amount of postgres data inserts decreased it, by sacrificing strong consistency for eventual consistency.

There are other points where data for Postgres is retrieved, but there's no limitation on usage of OMG.Bus.

**Comment by pnowosie** [comment] 2019-11-04 10:46
@unnawut 
>     2\. Strip all code from `elixir-omg-infoapi` except for the API endpoints that solely rely on Watcher DB (the postgres one).

This is hard one (as Ino pointed out) but also unnecessary because all Watcher's infoApi endpoints are supported by postgres data and no security feature relies on postgres data. This means once you managed to populate postgres without Watcher (from bus or otherwise) you're ready to drop all forked code.

> I'm very, very much convinced that splitting or stripping the current codebase is impossible

But we'll do the impossible anyway, right @InoMurko 😂

**Comment by unnawut** [comment] 2019-11-13 12:21
Gathering the discussions here before they get lost...

**Status updates:**

1. Security-critical API will rely `OMG.DB` for data. No calls to `OMG.Watcher.DB` or `OMG.WatcherInformational` (https://github.com/omisego/elixir-omg/pull/1123).

2. Informational API will rely on `OMG.Watcher.DB` for data. No calls to `OMG.DB` or `OMG.WatcherSecurity` (https://github.com/omisego/elixir-omg/pull/1123).

3. Informational API will populate its `OMG.Watcher.DB` via `OMG.Bus` only. No calls to/from any other subapps (https://github.com/omisego/elixir-omg/pull/1096).

4. Repo split will not happen at least until block explorer MVP is complete + API user personas, when we have better understanding of API usage.

5. The code split is blocking https://github.com/omisego/elixir-omg/issues/931, will figure how to unblock.

**Ongoing discussions:**

1. > @Pongch: Product and marketing is finalizing places for the personas to live so stay tune and you should be able to read more about how these guys consume our APIs in the wild.

2. Line between Watcher's critical vs. informational API. Current line is:

    - Informational: Have enough information for clients to make deposit, transfer and exit. 
    - Security-critical: Serve everything else that wants to engage in activities that preserve security of their funds or Network. This includes all sorts of challenges.

    But `/transaction.submit` is part of security-critical API. Ongoing at https://github.com/omisego/elixir-omg/issues/1129. API consumer personas will also help decide.

3. Feature-rich data API for block explorer, etc. goes with Informational API for now. Need to double check with personas.

**Comment by unnawut** [comment] 2019-11-21 10:00
Ongoing discussions/inputs regarding API split:

- Is transaction.submit security critical API? #1129
- Block explorer requirements #1001
- Update watcher /transaction.all endpoint output #954
- Include associated ethevents in each utxo returned by /account.get_utxos #1154

**Comment by unnawut** [comment] 2019-12-05 18:06
Closing this issue as majority of the discussion should already be covered in #1123. And given the length (and breadth) of this discussion it's likely worth opening new issues.

**Closed by unnawut** 2019-12-05 18:06 UTC
Labels: api
