### ISSUE TITLE
Transaction.submit_typed does not accept transaction paying the fee

### ISSUE THREAD

**Issue by pnowosie** [omisego/elixir-omg#1120] opened 2019-11-08 09:07 UTC
From omg-js integration work we discovered issue submit tx paying the fee in the same token that transaction transfers.

Here is what we do:
 tx.create :arrow_forward: sign the returned `sign_hash` :arrow_forward: tx.submit_typed

Observations
- transaction with zero-fee succeeds :heavy_check_mark: 
- transaction with non-zero-fee fails with `:unauthorized_spend` :no_entry: 
- submiting the same tx with non-zero-fee using `tx.submit` (construct tx from scratch, hash, sign, submit) succeeds :heavy_check_mark: 

I've checked that `tx.create` calculates both txs (with & without fees)  `sign_hash`-es correctly

**Comment by InoMurko** [comment] 2019-11-08 09:14
```
%{
  "data" => %{
    "result" => "complete",
    "transactions" => [
      %{
        "fee" => %{
          "amount" => 1,
          "currency" => "0x0000000000000000000000000000000000000000"
        },
        "inputs" => [
          %{
            "amount" => 1000000000000000000,
            "blknum" => 4,
            "currency" => "0x0000000000000000000000000000000000000000",
            "oindex" => 0,
            "owner" => "0x78e478dca2912d104d6315ddbdd26e964fa16612",
            "txindex" => 0,
            "utxo_pos" => 4000000000
          },
          %{
            "amount" => 1000000000000000000,
            "blknum" => 2,
            "currency" => "0x0000000000000000000000000000000000000000",
            "oindex" => 0,
            "owner" => "0x78e478dca2912d104d6315ddbdd26e964fa16612",
            "txindex" => 0,
            "utxo_pos" => 2000000000
          }
        ],
        "metadata" => nil,
        "outputs" => [
          %{
            "amount" => 1000000000000000000,
            "currency" => "0x0000000000000000000000000000000000000000",
            "owner" => "0xfa823a60cdce075890568781e7135447a39163db"
          },
          %{
            "amount" => 999999999999999999,
            "currency" => "0x0000000000000000000000000000000000000000",
            "owner" => "0x78e478dca2912d104d6315ddbdd26e964fa16612"
          }
        ],
        "sign_hash" => "0x189a2d6e160fe9bfb5d551f65a847709b901c7b44b1e763884dc76bc80e5a2f4",
        "txbytes" => "0xf89901ca84ee6b28008477359400f86af40194fa823a60cdce075890568781e7135447a39163db940000000000000000000000000000000000000000880de0b6b3a7640000f4019478e478dca2912d104d6315ddbdd26e964fa16612940000000000000000000000000000000000000000880de0b6b3a763ffffa00000000000000000000000000000000000000000000000000000000000000000",
        "typed_data" => %{
          "domain" => %{
            "name" => "OMG Network",
            "salt" => "0xfad5c7f626d80f9256ef01929f3beb96e058b8b4b0e3fe52d84f054c0e2a7a83",
            "verifyingContract" => "0xd17e1233a03affb9092d5109179b43d6a8828607",
            "version" => "1"
          },
          "message" => %{
            "input0" => %{"blknum" => 4, "oindex" => 0, "txindex" => 0},
            "input1" => %{"blknum" => 2, "oindex" => 0, "txindex" => 0},
            "input2" => %{"blknum" => 0, "oindex" => 0, "txindex" => 0},
            "input3" => %{"blknum" => 0, "oindex" => 0, "txindex" => 0},
            "metadata" => "0x0000000000000000000000000000000000000000000000000000000000000000",
            "output0" => %{
              "amount" => 1000000000000000000,
              "currency" => "0x0000000000000000000000000000000000000000",
              "owner" => "0xfa823a60cdce075890568781e7135447a39163db"
            },
            "output1" => %{
              "amount" => 999999999999999999,
              "currency" => "0x0000000000000000000000000000000000000000",
              "owner" => "0x78e478dca2912d104d6315ddbdd26e964fa16612"
            },
            "output2" => %{
              "amount" => 0,
              "currency" => "0x0000000000000000000000000000000000000000",
              "owner" => "0x0000000000000000000000000000000000000000"
            },
            "output3" => %{
              "amount" => 0,
              "currency" => "0x0000000000000000000000000000000000000000",
              "owner" => "0x0000000000000000000000000000000000000000"
            }
          },
          "primaryType" => "Transaction",
          "types" => %{
            "EIP712Domain" => [
              %{"name" => "name", "type" => "string"},
              %{"name" => "version", "type" => "string"},
              %{"name" => "verifyingContract", "type" => "address"},
              %{"name" => "salt", "type" => "bytes32"}
            ],
            "Input" => [
              %{"name" => "blknum", "type" => "uint256"},
              %{"name" => "txindex", "type" => "uint256"},
              %{"name" => "oindex", "type" => "uint256"}
            ],
            "Output" => [
              %{"name" => "outputType", "type" => "uint256"},
              %{"name" => "outputGuard", "type" => "bytes20"},
              %{"name" => "currency", "type" => "address"},
              %{"name" => "amount", "type" => "uint256"}
            ],
            "Transaction" => [
              %{"name" => "txType", "type" => "uint256"},
              %{"name" => "input0", "type" => "Input"},
              %{"name" => "input1", "type" => "Input"},
              %{"name" => "input2", "type" => "Input"},
              %{"name" => "input3", "type" => "Input"},
              %{"name" => "output0", "type" => "Output"},
              %{"name" => "output1", "type" => "Output"},
              %{"name" => "output2", "type" => "Output"},
              %{"name" => "output3", "type" => "Output"},
              %{"name" => "metadata", "type" => "bytes32"}
            ]
          }
        }
      }
    ]
  },
  "service_name" => "watcher",
  "success" => true,
  "version" => "0.3.0+288326b"
}
Alice sends Bob funds ---> ok
All features passed.
```
with two signatures:
```
def submit_transaction(typed_data, sign_hash, private_key) do
    signature =
      sign_hash
      |> Encoding.to_binary()
      |> Encoding.signature_digest(private_key)

    typed_data_signed = Map.put_new(typed_data, "signatures", [Encoding.to_hex(signature), Encoding.to_hex(signature)])

    submit_typed(typed_data_signed)
  end
```

**Comment by InoMurko** [comment] 2019-11-08 09:29
Why does this test not need two signatures?
https://github.com/omisego/elixir-omg/blob/master/apps/omg_watcher/test/omg_watcher/integration/transaction_submit_test.exs#L79-L81

**Comment by kevsul** [comment] 2019-11-08 10:07
Because the value of the transaction + the fee are both covered by one input. One input -> one signature

**Comment by kevsul** [comment] 2019-11-08 12:32
Ok, found the problem. Nothing specifically to do with fees, the issue is to do with big numbers and adding a fee just made that happen.
So, in the failing test case, there's an output 
```
{
  "amount": 2799999989999999990,
  "currency": "0x0000000000000000000000000000000000000000",
  "owner": "0xf86b5b1c2c8de1ea4dc737c849272340fa3561c5"
}
```

That `2799999989999999990` is larger than MAX_SAFE_INTEGER in javascript. It's not a problem in the library code because we use a BigNumber class to deal with it.

But when it's written back to json to send it to `transaction.submit_typed` it needs to be converted to a Number, which loses precision and rounds it up to `2799999990000000000`.
So the typed_data field in the `submit_typed` is wrong, which causes the `unauthorized_spend` error.

Unfortunately, the only way I can think of to fix this is to convert all numbers to strings in the JSON data. Anyone got any better ideas?

**Comment by jarindr** [comment] 2019-11-08 13:19
@kevsul either `string` or `hex` should be fine then get parse back on watcher side.

**Comment by kevsul** [comment] 2019-11-08 13:39
> Anyone got any better ideas?

The better idea is to just leave them as Big Numbers and use the `json-bigint` package to write out the JSON. No conversion to Number involved, so no precision loss

**Comment by kevsul** [comment] 2019-11-08 14:51
Closing this. Fixed on client side

**Closed by kevsul** 2019-11-08 14:51 UTC
