### ISSUE TITLE
Modification of Childchain behaviour to support Infura & Secure Signing

### ISSUE THREAD

**Issue by jbunce** [omisego/elixir-omg#1029] opened 2019-10-03 11:04 UTC
1) We need to be able to connect to Infura for development deployments. This will let us turn up environments faster without having to wait for nodes to sync and deal with the associated stability problems we've encountered. To enable this operation we'll need the Childchain to sign transactions before submitting to Infura, as they don't support key management.

Proposed ENV to enable behaviour: `ETH_NODE: infura`

2) Block submissions will need to change from the current RPC call to an authenticated HTTPS call. POST data inside this call will have to include the data that will be signed by the secure signing mechanism and then forwarded to Infura.

Proposed ENV to enabled behaviour: `ETH_NODE: secure_signing`

**Comment by InoMurko** [comment] 2019-10-15 07:18
@jbunce can you expand on that second part?
```

    Block submissions will need to change from the current RPC call to an authenticated HTTPS call. POST data inside this call will have to include the data that will be signed by the secure signing mechanism and then forwarded to Infura.

```

**Comment by InoMurko** [comment] 2019-10-15 07:20
ok #2 is not ready yet as of now. Proceeding infura without it.

**Comment by InoMurko** [comment] 2019-12-18 13:32
We're supporting infura already. The second part of the issue is equal to: https://github.com/omisego/elixir-omg/issues/1092
So I'll close this. Re-open if you don't think so.

**Closed by InoMurko** 2019-12-18 13:32 UTC
