### ISSUE TITLE
Standalone Watcher deployment

### ISSUE THREAD

**Issue by achiurizo** [omisego/elixir-omg#718] opened 2019-05-23 03:17 UTC
:clipboard: [PLAN-226](https://omisego.atlassian.net/browse/PLAN-226)

As a user, I would like to easily deploy a standalone Watcher, so that I can validate transactions myself without relying on 3rd party.

**Comment by pdobacz** [comment] 2019-05-23 07:49
duplicate of #713 ?

**Closed** 2019-05-23 08:54 UTC
